CREATE TABLE IF NOT EXISTS EMPLOYEE (
  ID INTEGER PRIMARY KEY, -- Alias for ROWID
  NAME TEXT NOT NULL,
  SURNAME TEXT NOT NULL,
  DOCUMENT TEXT NOT NULL,
  SECTOR TEXT NOT NULL,
  GROSS_WAGE TEXT NOT NULL,
  ADMISSION_DATE TEXT NOT NULL,
  HAS_HEALTHCARE BOOL NOT NULL CHECK(HAS_HEALTHCARE IN (0, 1)),
  HAS_DENTALCARE BOOL NOT NULL CHECK(HAS_DENTALCARE IN (0, 1)),
  HAS_TRANSPORTATION_ALLOWANCE BOOL NOT NULL CHECK(HAS_TRANSPORTATION_ALLOWANCE IN (0, 1))
);

CREATE INDEX IF NOT EXISTS IDX_EMPLOYEE ON EMPLOYEE(ID);
